package com;// Generated by Selenium IDE

import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.Map;
public class CreateUserOrganizer {
//    private static WebDriver driver = null;
//    private Map<String, Object> vars;
//    JavascriptExecutor js;
//    @BeforeClass
//    public static void setUp() {
//        driver = new ChromeDriver();
//        js = (JavascriptExecutor) driver;
//        vars = new HashMap<String, Object>();
//        System.setProperty("webdriver.gecko.driver", "E:\\UPC\\Ciclo7\\Diseño de Experimentos ISW\\frikiteam\\frikievents-back\\geckodriver.exe");
//        driver = new FirefoxDriver();
//    }
//    @After
//    public void tearDown() {
//        driver.quit();
//    }
    @Test
    public void registrarse() {
//        driver.get("http://localhost:4200/");
//        driver.manage().window().setSize(new Dimension(1440, 780));
//        driver.findElement(By.cssSelector(".mat-menu-trigger .mat-icon")).click();
//        driver.findElement(By.id("RegisterOption")).click();
//        driver.findElement(By.id("mat-input-1")).click();
//        driver.findElement(By.id("mat-input-1")).sendKeys("usuarioorganizador1@gmail.com");
//        driver.findElement(By.id("mat-input-2")).click();
//        driver.findElement(By.id("mat-input-2")).sendKeys("Usuario");
//        driver.findElement(By.cssSelector(".ng-tns-c93-5 > .mat-form-field-infix")).click();
//        {
//            WebElement element = driver.findElement(By.cssSelector("path"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
//        driver.findElement(By.id("mat-input-3")).sendKeys("Orga");
//        driver.findElement(By.cssSelector("path")).click();
//        {
//            WebElement element = driver.findElement(By.tagName("body"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element, 0, 0).perform();
//        }
//        {
//            WebElement element = driver.findElement(By.cssSelector(".mat-calendar-arrow"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
//        driver.findElement(By.cssSelector(".mat-calendar-arrow")).click();
//        {
//            WebElement element = driver.findElement(By.tagName("body"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element, 0, 0).perform();
//        }
//        driver.findElement(By.cssSelector(".mat-calendar-previous-button")).click();
//        driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content")).click();
//        driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content")).click();
//        driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(1) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).click();
//        driver.findElement(By.cssSelector(".ng-tns-c93-7 > .mat-form-field-infix")).click();
//        {
//            WebElement element = driver.findElement(By.cssSelector(".btn-submit"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
//        driver.findElement(By.id("mat-input-5")).sendKeys("contraseñagenerica1");
//        driver.findElement(By.cssSelector(".btn-submit")).click();
//        {
//            WebElement element = driver.findElement(By.tagName("body"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element, 0, 0).perform();
//        }
    }
}

