// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-focus-indicator:nth-child(5) > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".button > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".ng-tns-c93-4 > .mat-form-field-infix")).click();
    driver.findElement(By.cssSelector(".ng-tns-c93-4 > .mat-form-field-infix")).click();
    driver.findElement(By.id("mat-input-1")).click();
    driver.findElement(By.id("mat-input-1")).sendKeys("Evento Friki");
    driver.findElement(By.id("mat-input-2")).sendKeys("C.C. Arenales");
    driver.findElement(By.id("mat-input-3")).click();
    driver.findElement(By.id("mat-input-3")).sendKeys("C.C. Arenales");
    driver.findElement(By.id("mat-input-4")).click();
    driver.findElement(By.id("mat-input-4")).sendKeys("Lima");
    driver.findElement(By.cssSelector(".ng-tns-c93-14 > .mat-form-field-infix")).click();
    driver.findElement(By.id("mat-input-5")).sendKeys("20");
    driver.findElement(By.id("mat-input-6")).click();
    driver.findElement(By.id("mat-input-6")).sendKeys("200");
    driver.findElement(By.cssSelector(".ng-tns-c93-16 > .mat-form-field-infix")).click();
    driver.findElement(By.id("mat-date-range-input-0")).sendKeys("02/05/2022");
    driver.findElement(By.cssSelector(".mat-end-date")).sendKeys("20/05/2022");
    driver.findElement(By.cssSelector(".creation-content .container")).click();
    driver.findElement(By.cssSelector(".btn-submit > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".btn-submit > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".btn-submit > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-submit > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
